// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	m_member "main.go/db/m-member"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, member
func (_m *Service) Add(ctx context.Context, member m_member.MerchantMember) error {
	ret := _m.Called(ctx, member)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, m_member.MerchantMember) error); ok {
		r0 = rf(ctx, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, email
func (_m *Service) Delete(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByMerchantID provides a mock function with given fields: ctx, mID
func (_m *Service) DeleteByMerchantID(ctx context.Context, mID string) error {
	ret := _m.Called(ctx, mID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, mID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, email
func (_m *Service) Get(ctx context.Context, email string) (*m_member.MerchantMemberEntity, error) {
	ret := _m.Called(ctx, email)

	var r0 *m_member.MerchantMemberEntity
	if rf, ok := ret.Get(0).(func(context.Context, string) *m_member.MerchantMemberEntity); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*m_member.MerchantMemberEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByMerchantID provides a mock function with given fields: ctx, mID, offset, limit
func (_m *Service) GetByMerchantID(ctx context.Context, mID string, offset int, limit int) ([]m_member.MerchantMemberEntity, error) {
	ret := _m.Called(ctx, mID, offset, limit)

	var r0 []m_member.MerchantMemberEntity
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []m_member.MerchantMemberEntity); ok {
		r0 = rf(ctx, mID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]m_member.MerchantMemberEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, mID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsExisted provides a mock function with given fields: ctx, email
func (_m *Service) IsExisted(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, member
func (_m *Service) Update(ctx context.Context, member m_member.MerchantMember) error {
	ret := _m.Called(ctx, member)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, m_member.MerchantMember) error); ok {
		r0 = rf(ctx, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
